# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1614b54674ea3760972a4cc0a818d4b7f8675ce1c34b2ebb55dc170a0c71d0852b9747cfd0b6df6c2f1be92ee618d57e486ddb948404e2f6f2f53cbf6609748

test:
  secret_key_base: 13114b46990058a4d25d60a9b40ec8ea623d6e333520a6858b5dc9b83c525e9454aaca24ba8f16a0d88eba24da47250b4d079fba5f32065f1bfc49dc8eb722a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
